export const tableHead: any[] = [
  {
    nonDoctors: ["id", "name", "department", "email"],
    ongoingAppointment: [
      "id",
      "Image",
      "appointmentName",
      "status",
      "Budget",
      "EndDate",
      "location",
    ],
    nonfacilitator: [
      "facilitatorId",
      "profileImg",
      "fullName",
      "mobileNo",
      "email",
    ],
    facilitator: [
      "facilitatorId",
      "profileImg",
      "fullName",
      "mobileNo",
      "email",
      "noOfDoctor",
      "status",
      "rating",
    ],
    nonfacilitatorList: [
      "id",
      "Image",
      "listName",
      "OwnedBy",
      "mobileNo",
      "Amount",
      "categoryType",
      "isVerified",
    ],
    facilitatorList: [
      "id",
      "Image",
      "listName",
      "OwnedBy",
      "mobileNo",
      "categoryType",
      "Amount",
      "status",
    ],
    facilitatorListOnFacilitatorProfile: [
      "id",
      "Image",
      "listName",
      "categoryType",
      "Amount",
      "location",
      "JoinedDate",
      "status",
    ],
    userList: [
      // for userListing Page Table
      "id",
      "image",
      "name",
      "mobileNo",
      "status",
    ],
    userAppointments: [
      // for eventList User Event
      "id",
      "Image",
      "Name",
      "City",
      "ProgramCount",
      "StartDate",
      "CategoryType",
      "SubCategory",
      "EndDate",
    ],
    appointmentList: [
      "id",
      "status",
      "patientName",
      "hospital",
      "doctorName",
      "department",
      "booking_StartDate",
      "booking_EndDate",
    ],
    complaintBox: [
      "id",
      "ReportedBy",
      "MobileNo",
      "userType",
      "createdDate",
      "message",
      "status",
    ],
    quote: [
      "id",
      "userName",
      "listName",
      "facilitatorName",
      "appointmentName",
      "userBudget",
      "facilitatorQuote",
      "status",
    ],
    recentFacilitators: ["id", "name", "mobileNo"],
    recentUsers: ["id", "name", "mobileNo"],
    reports: {
      user: [
        "id",
        "Image",
        "Name",
        "mobileNo",
        "email",
        "Invitations",
        "shortlists",
        "NoOfAppointmentsAttended",
        "NoOfReviews",
        "joinedDate",
        "status",
      ],
      facilitator: [
        "id",
        "Image",
        "Name",
        "mobileNo",
        "email",
        "location",
        "NoOfdoctors",
        "NoOfProgramsAttended",
        "NoOfAppointmentsDeclined",
        "NoOfProgramByQuote",
        "NoOfProgramByDirect",
        "JoinedDate",
        "status",
      ],
      list: [
        "id",
        "Name",
        "ownedBy",
        "price",
        "categoryType",
        "serveState",
        "serveCountry",
        "NoOfAppointmentsAttended",
        "NoOfAppointmentsDeclined",
        "NoOfProgramByQuote",
        "NoOfProgramByDirect",
        "status",
        "JoinedDate",
      ],
      appointment: [
        "id",
        "Name",
        "ownedBy",
        "NoOfFacilitators",
        "NoOfPrograms",
        "Budget",
        "AppointmentType",
        "location",
        "status",
        "JoinedDate",
      ],
    },
  },
];
